services:
  sqlserver:
    build:
      context: "./"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - "1435:1433" # Maps port 1434 on the host to 1433 in the container
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql_data:
    driver: local
